spring.application.name=api-gateway
server.port=8080

# Routes
user.service.url=http://localhost:8081
payment.service.url=http://localhost:8083
wallet.service.url=http://localhost:8082
notification.service.url=http://localhost:8084

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT (same secret as user-service!)
jwt.secret=smartpay-user-service-secret-key-2024-very-long-string