# App
spring.application.name=api-gateway
server.port=8080

# Redis (for rate limiting)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=smartpay-user-service-secret-key-2024-very-long-string

# Service URLs
services.user=http://localhost:8081
services.payment=http://localhost:8082
services.wallet=http://localhost:8083
services.notification=http://localhost:8084