# App
spring.application.name=payment-service
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_service_db
spring.datasource.username=vickyshetty
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Redis (for idempotency keys)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=smartpay-user-service-secret-key-2024-very-long-string